# Generated by Django 2.1.5 on 2019-01-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imageurl',
            field=models.CharField(default=1, max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
