# Generated by Django 2.1.5 on 2019-01-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190130_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(choices=[('John', 'John'), ('Dev', 'Dev'), ('Amy', 'Amy'), ('Eva', 'Eva')], max_length=50),
        ),
    ]
