# Generated by Django 2.1.5 on 2019-01-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190130_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imageurl',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
