# Generated by Django 2.1.5 on 2019-01-31 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190131_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(choices=[('John', 'John'), ('Dev', 'Dev'), ('Amy', 'Amy'), ('Eva', 'Eva')], max_length=50),
        ),
    ]
