# Generated by Django 2.1.5 on 2019-01-31 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='author',
            new_name='title',
        ),
    ]
