# Generated by Django 2.1.5 on 2019-01-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190131_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Games', 'Games'), ('Lifestyle', 'Lifestyle'), ('Sports', 'Sports'), ('Developer', 'Developer'), ('Food', 'Food'), ('Travel', 'Travel'), ('Movies', 'Movies'), ('Photography', 'Photography/Filmography')], default='Not Categorized', max_length=15),
        ),
    ]
