# Generated by Django 2.1.5 on 2019-01-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_commentcounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='commentcounter',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
