# Generated by Django 2.1.5 on 2019-02-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uploadimg',
            field=models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
