# Generated by Django 2.1.5 on 2019-02-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_uploadimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.SlugField(max_length=100),
        ),
    ]
