# Generated by Django 2.1.5 on 2019-02-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20190201_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.SlugField(editable=False, max_length=100, unique=True),
        ),
    ]
