# Generated by Django 2.1.5 on 2019-02-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20190208_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='commentcounter',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
