# Generated by Django 2.1.5 on 2019-02-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20190208_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='commentcounter',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
