# Generated by Django 2.1.5 on 2019-02-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20190208_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='commentcounter',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
